feat: optimize ci-core build cache

diff --git a/tools/bin/go_core_race_tests b/tools/bin/go_core_race_tests
--- a/tools/bin/go_core_race_tests
+++ b/tools/bin/go_core_race_tests
@@ -5,19 +5,26 @@ USE_TEE="${USE_TEE:-true}"
 TIMEOUT="${TIMEOUT:-30s}"
 COUNT="${COUNT:-10}"
 
-# To allow reuse in CI from other repositories
-TOOLS_PATH=${TOOLS_PATH:-"./tools"}
-
-GO_LDFLAGS=$(bash ${TOOLS_PATH}/bin/ldflags)
-use_tee() {
-  if [ "$USE_TEE" = "true" ]; then
-    tee "$@"
-  else
-    cat > "$@"
-  fi
-}
-GORACE="log_path=$PWD/race" go test -json -race -ldflags "$GO_LDFLAGS" -shuffle on -timeout "$TIMEOUT" -count "$COUNT" $1 | use_tee "$OUTPUT_FILE"
 EXITCODE=${PIPESTATUS[0]}
+
+echo "Failed tests and panics: ---------------------"
+echo ""
+if [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
+  if [ "$DEBUG" == "true" ]; then 
+    GORACE="log_path=$PWD/race" go test -json -vet=off -race -shuffle on -timeout "$TIMEOUT" -count "$COUNT" $1 | tee $OUTPUT_FILE
+  else
+    GORACE="log_path=$PWD/race" go test -json -vet=off -race -shuffle on -timeout "$TIMEOUT" -count "$COUNT" $1 | cat > $OUTPUT_FILE
+  fi
+else
+  if [ "$DEBUG" == "true" ]; then 
+        GORACE="log_path=$PWD/race" go test -json -vet=off -race -shuffle on -timeout "$TIMEOUT" -count "$COUNT" $1 | tee $OUTPUT_FILE
+  else
+    GORACE="log_path=$PWD/race" go test -json -vet=off -race -shuffle on -timeout "$TIMEOUT" -count "$COUNT" $1 | cat > $OUTPUT_FILE
+  fi
+fi
+EXITCODE=${PIPESTATUS[0]}
+
+
 # Fail if any race logs are present.
 if ls race.* &>/dev/null
 then
