Fix

diff --git a/.github/workflows/find-new-flaky-tests.yml b/.github/workflows/find-new-flaky-tests.yml
--- a/.github/workflows/find-new-flaky-tests.yml
+++ b/.github/workflows/find-new-flaky-tests.yml
@@ -253,36 +253,34 @@ jobs:
 
       - name: Set combined test results
         id: set_test_results
+        shell: bash
         run: |
+          set -e  # Exit immediately if a command exits with a non-zero status.
           if [ -d "test_results" ]; then
             cd test_results
             ls -R .
-            # Combine JSON files into one file and sort in ascending order by PassRatio
             find . -name '*.json' -exec cat {} + | jq -s 'add | sort_by(.PassRatio)' > all_tests.json
-            # Save all tests count
-            echo "all_tests_count=$(jq 'length' all_tests.json)" >> "$GITHUB_OUTPUT"
-            # Save failed tests results and count
+            ALL_TESTS_COUNT=$(jq 'length' all_tests.json)
+            echo "All tests count: $ALL_TESTS_COUNT"
+            echo "all_tests_count=$ALL_TESTS_COUNT" >> "$GITHUB_OUTPUT"
             jq -c 'map(select(.PassRatio < ($runThreshold | tonumber))) | map(.PassRatio |= (. * 100 | tostring + "%"))' all_tests.json --arg runThreshold '${{ inputs.runThreshold }}' > failed_tests.json
-            echo "failed_tests_count=$(jq 'length' failed_tests.json)" >> "$GITHUB_OUTPUT"
+            FAILED_TESTS_COUNT=$(jq 'length' failed_tests.json)
+            echo "Failed tests count: $FAILED_TESTS_COUNT"
+            echo "failed_tests_count=$FAILED_TESTS_COUNT" >> "$GITHUB_OUTPUT"
           else
             echo "No test results directory found."
+            echo "[]" > test_results/all_tests.json
+            echo "[]" > test_results/failed_tests.json
             echo "all_tests_count=0" >> "$GITHUB_OUTPUT"
             echo "failed_tests_count=0" >> "$GITHUB_OUTPUT"
           fi
-
+      
       - name: Create ASCII table with failed test results
         if: ${{ fromJson(steps.set_test_results.outputs.failed_tests_count) > 0 }}
         shell: bash
         run: |
-          jq -r '["TestPackage", "TestName", "PassRatio", "RunCount"], ["---------", "---------", "---------", "---------"], (.[] | [.TestPackage, .TestName, .PassRatio, .Runs]) | @tsv' failed_tests.json | column -t -s$'\t' > failed_tests_ascii.txt
-          cat failed_tests_ascii.txt        
-
-      - name: Create ASCII table with all test results
-        if: ${{ fromJson(steps.set_test_results.outputs.all_tests_count) > 0 }}
-        shell: bash
-        run: |
-          jq -r '["TestPackage", "TestName", "PassRatio", "RunCount"], ["---------", "---------", "---------", "---------"], (.[] | [.TestPackage, .TestName, .PassRatio, .Runs]) | @tsv' all_tests.json | column -t -s$'\t' > all_tests_ascii.txt
-          cat all_tests_ascii.txt        
+          jq -r '["TestPackage", "TestName", "PassRatio", "RunCount"], ["---------", "---------", "---------", "---------"], (.[] | [.TestPackage, .TestName, .PassRatio, .Runs]) | @tsv' test_results/failed_tests.json | column -t -s$'\t' > test_results/failed_tests_ascii.txt
+          cat test_results/failed_tests_ascii.txt
 
       - name: Create GitHub Summary
         run: |
@@ -319,7 +317,7 @@ jobs:
           echo "### Failed Tests :x:" >> $GITHUB_STEP_SUMMARY
           echo "Ran \`${{ steps.set_test_results.outputs.all_tests_count }}\` tests in total for all affected test packages. Below are the tests identified as flaky, with a pass ratio lower than the \`${threshold_percentage}%\` threshold:" >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
-          cat failed_tests_ascii.txt >> $GITHUB_STEP_SUMMARY
+          cat test_results/failed_tests_ascii.txt >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
 
       - name: Append Success Note if All Tests Passed
